"""Generate RETRIEVAL.md: what was retrieved, and what was not.

    .venv/bin/python scripts/retrieval_report.py                  # disk only
    .venv/bin/python scripts/retrieval_report.py --verify         # + archive

Disk coverage answers "did we download everything we expected?". It cannot
distinguish our failure from ERCOT's: a publication absent from `data/raw`
might never have been posted. `--verify` asks the archive listing what it
holds for each day, which separates the two and costs one request per day.

Run without credentials for the offline half; the committed report carries the
verified answer.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from forecast_spine import coverage, ercot

RAW = Path("data/raw")

# The assignment's windows.
FORECAST_WINDOW = (dt.date(2026, 2, 21), dt.date(2026, 3, 23))
TARGET_WINDOW = (dt.date(2026, 2, 22), dt.date(2026, 3, 23))
# Actuals must cover the target days and the seven-day seasonal-naive
# lookback before the first of them; each operating day posts the next morning.
ACTUAL_WINDOW = (dt.date(2026, 2, 16), dt.date(2026, 3, 24))

WINDOWS = {"load_forecast": FORECAST_WINDOW, "actual_load": ACTUAL_WINDOW}


def archive_counts(report_key: str, start: dt.date, end: dt.date) -> dict[dt.date, int]:
    """How many publications ERCOT's archive lists per local day."""
    from forecast_spine import ercot_api

    client = ercot_api.ErcotApiClient(ercot_api.Credentials.from_env(Path(".env")))
    report = ercot.REPORTS[report_key]
    counts: dict[dt.date, int] = {}
    for entry in client.list_archives(report, start, end):
        day = entry.post_datetime_utc.astimezone(coverage.CENTRAL).date()
        counts[day] = counts.get(day, 0) + 1
    return counts


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true",
                        help="Ask the archive what it holds (needs credentials).")
    parser.add_argument("--out", default="RETRIEVAL.md")
    args = parser.parse_args()

    lines = [
        "# Retrieval statement",
        "",
        "Generated by `scripts/retrieval_report.py`. Every figure is counted from",
        "the files in `data/raw`, not recalled.",
        "",
        f"Target hours: **{TARGET_WINDOW[0]} - {TARGET_WINDOW[1]}** inclusive, Central.",
        "",
    ]

    for report_key, (start, end) in WINDOWS.items():
        report = ercot.REPORTS[report_key]
        result = coverage.measure(report_key, start, end, RAW)
        listed = archive_counts(report_key, start, end) if args.verify else {}

        pct = 100.0 * result.held / result.expected if result.expected else 100.0
        lines += [
            f"## {report.product_id} — {report.title}",
            "",
            f"Requested window: **{start} .. {end}** (local publication days)  ",
            (
                f"Retrieved: **{result.held} / {result.expected}** expected "
                f"publications ({pct:.1f}%)"
            ),
            "",
        ]

        incomplete = [d for d in result.days if not d.complete]
        if not incomplete:
            lines += ["Complete: every expected publication is on disk.", ""]
            continue

        ours = [d for d in incomplete if listed.get(d.day, d.held) > d.held]
        theirs = [d for d in incomplete if listed.get(d.day, d.held) <= d.held]

        lines += [
            f"{len(incomplete)} day(s) hold fewer publications than the cadence implies.",
            "",
            "| local day | expected | retrieved | listed by ERCOT | gap |",
            "| --- | ---: | ---: | ---: | --- |",
        ]
        for day in incomplete:
            listed_count = listed.get(day.day)
            shown = str(listed_count) if listed_count is not None else "not checked"
            if listed_count is None:
                verdict = "unknown"
            elif listed_count <= day.held:
                verdict = "never published"
            else:
                verdict = "not retrieved"
            lines.append(
                f"| {day.day} | {day.expected} | {day.held} | {shown} | {verdict} |"
            )
        lines.append("")
        if args.verify:
            lines += [
                (
                    f"**{len(theirs)} day(s) are gaps in ERCOT's archive itself** — the "
                    "listing offers no more than we hold, so those publications cannot be "
                    "retrieved by anyone."
                ),
                "",
            ]
            if ours:
                lines += [
                    (
                        f"**{len(ours)} day(s) are ours to fix** — the listing offers more "
                        "than we downloaded. Re-run `forecast-spine backfill` for those dates."
                    ),
                    "",
                ]
        lines += [
            "Missing publication hours (first 20):",
            "",
            "```",
            *[f"{m:%Y-%m-%d %H:%M %Z}" for m in result.missing_hours[:20]],
            *([f"... and {len(result.missing_hours) - 20} more"]
              if len(result.missing_hours) > 20 else []),
            "```",
            "",
        ]

    lines += [
        "## Effect on the evaluation",
        "",
        "A missing publication is not automatically a missing forecast: the as-of rule",
        "takes the newest vintage published at or before `T - 24h`, so a gap only shows",
        "up when it removes the last eligible vintage for a target hour, or leaves one",
        "older than the readiness gate's staleness limit. The gate reports both, per",
        "zone-hour, in `data/reports/`.",
        "",
    ]

    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
